# Generated by Django 5.2.2 on 2025-06-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namn', models.CharField(max_length=100, unique=True)),
                ('kortnamn', models.CharField(max_length=20)),
                ('orderbook_id', models.CharField(max_length=20)),
                ('valuta', models.CharField(max_length=10)),
                ('landkod', models.CharField(max_length=2)),
                ('marketplace', models.CharField(max_length=10)),
                ('senaste_pris', models.FloatField()),
                ('market_cap_msek', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_rubrik', models.CharField(max_length=255)),
                ('trigger_beskrivning', models.TextField()),
                ('trigger_referens', models.URLField()),
                ('kurspaverkan', models.CharField(choices=[('låg', 'Låg'), ('mellan', 'Mellan'), ('hög', 'Hög'), ('gigantisk', 'Gigantisk')], max_length=10)),
                ('trigger_datum', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='triggers.stock')),
            ],
        ),
    ]
