# Generated by Django 5.2.2 on 2025-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrigger',
            name='trigger_datum_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
